export default [
    {
        id: 1,
        name: "CRM",
        github: "https://github.com/handcode-stuart/crm",
        website: "https://www.handcode.co.uk",
        bio:
            "A custom CRM built with a NodeJS/Express server & API, using React for the UI, Redux for state management and JWT across front/back-end for authentication.",
        tech: "React, Redux, NodeJS, Express, Axios, JWT, MongoDB, Jest, Enzyme, Styled Components",
        grad: ["#C6FFDD", "#f7797d"],
    },
    {
        id: 2,
        name: "Orderly",
        github: "https://github.com/handcode-stuart/orderly",
        website: "https://intense-falls-38018.herokuapp.com",
        bio:
            "An in-depth task management app that can track tasks, projects and tags to manage any project. Built with a NodeJS/Express server & API, using React for the UI, Redux for state management and JWT across front/back-end for authentication.",
        tech: "React, Redux, NodeJS, Express, Axios, JWT, MongoDB",
        grad: ["#FF0099", "#493240"],
    },
    {
        id: 3,
        name: "Worktop",
        github: "https://github.com/handcode-stuart/handcode-worktop",
        website: "https://worktop.handcode.co.uk/",
        bio:
            "A place to collect all of my projects/snippets that aren't large/polished enough to make it on my portfolio.",
        tech: "React, Styled Components",
        grad: ["#CB356B", "#BD3F32"],
    },
    {
        id: 4,
        name: "FPL stats",
        github: "https://github.com/handcode-stuart/fpl-stats",
        website: "https://trusting-fermi-8db60e.netlify.com",
        bio:
            "Using the now deprecated Fantasy Premier League API, this app was a way of seeing the player, team and match data in a different light to how the offical app showed.",
        tech: "React, Fantasy Premier League API",
        grad: ["#bc4e9c", "#f80759"],
    },
    {
        id: 5,
        name: "Sales Taxes",
        github: "https://github.com/handcode-stuart/sales_taxes",
        website: "https://protected-taiga-99206.herokuapp.com",
        bio: "A 'mock' store to show a simple tax calculator when a user puts items in their cart.",
        tech: "React, Redux, SCSS",
        grad: ["#159957", "#155799"],
    },
    {
        id: 6,
        name: "Spotify clone",
        github: "https://github.com/handcode-stuart/spotify-clone",
        website: "https://handcode-spotify-clone.herokuapp.com",
        bio: "An attempt to mimic the Spotify UI as closely as I can.",
        tech: "React, SCSS",
        grad: ["#007991", "#78ffd6"],
    },
    {
        id: 7,
        name: "Duckr",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#3494E6", "#EC6EAD"],
    },
    {
        id: 8,
        name: "Smart task input",
        github: "https://github.com/handcode-stuart/smart-task-input-react-component",
        website: "",
        bio: "",
        tech: "React",
        grad: ["#EECDA3", "#EF629F"],
    },
    {
        id: 9,
        name: "Swansea FC Interactive",
        github: "https://github.com/handcode-stuart/swanseafc-interactive",
        website: "https://admiring-bohr-1725f5.netlify.com",
        bio: "",
        tech: "React",
        grad: ["#FF5F6D", "#FFC371"],
    },
    {
        id: 10,
        name: "ReactNodeAuth",
        github: "",
        website: "",
        bio: "",
        tech: "React, NodeJS, Express, JWT",
        grad: ["#833ab4", "#fcb045"],
    },
    {
        id: 11,
        name: "Site Saver",
        github: "",
        website: "",
        bio: "",
        tech: "VueJS, Laravel",
        grad: ["#83a4d4", "#b6fbff"],
    },
    {
        id: 12,
        name: "Colllab",
        github: "",
        website: "",
        bio: "",
        tech: "VueJS, Laravel",
        grad: ["#ddd6f3", "#faaca8"],
    },
    {
        id: 13,
        name: "Guestlist app",
        github: "",
        website: "",
        bio: "",
        tech: "React, Laravel",
        grad: ["#FC354C", "#0ABFBC"],
    },
    {
        id: 14,
        name: "NextJS test",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#ED4264", "#FFEDBC"],
    },
    {
        id: 15,
        name: "User app",
        github: "https://github.com/handcode-stuart/user-app",
        website: "https://stupefied-jackson-7ac0fd.netlify.com",
        bio: "",
        tech: "",
        grad: ["#800080", "#ffc0cb"],
    },
    {
        id: 16,
        name: "Map User Data",
        github: "https://github.com/handcode-stuart/map-user-data",
        website: "https://peaceful-pike-e61c64.netlify.com",
        bio: "",
        tech: "React, Redux, Custom hooks",
        grad: ["#0cebeb", "#29ffc6"],
    },
];
