export default [
    {
        id: "crm",
        name: "CRM",
        github: "https://github.com/handcode-stuart/crm",
        website: "",
        bio:
            "A custom CRM built with a NodeJS/Express server & API, using React for the UI, Redux for state management and JWT across front/back-end for authentication.",
        tech: "React, Redux, NodeJS, Express, Axios, JWT, MongoDB, Jest, Enzyme, Styled Components",
        grad: ["#C6FFDD", "#f7797d"],
    },
    {
        id: "orderly",
        name: "Orderly",
        github: "https://github.com/handcode-stuart/orderly",
        website: "https://intense-falls-38018.herokuapp.com",
        bio:
            "An in-depth task management app that can track tasks, projects and tags to manage any project. Built with a NodeJS/Express server & API, using React for the UI, Redux for state management and JWT across front/back-end for authentication.",
        tech: "React, Redux, NodeJS, Express, Axios, JWT, MongoDB",
        grad: ["#FF0099", "#493240"],
    },
    {
        id: "draggable-todos",
        name: "Draggable Todo's",
        github: "https://github.com/handcode-stuart/draggable-todos",
        website: "https://quirky-pasteur-4e5d24.netlify.com/",
        bio: "A simple app that allows users to drag and drop items on a page.",
        tech: "React, React-Beautiful-DND",
        grad: ["#ddd6f3", "#faaca8"],
    },
    {
        id: "worktop",
        name: "Worktop",
        github: "https://github.com/handcode-stuart/handcode-worktop",
        website: "https://worktop.handcode.co.uk/",
        bio:
            "A place to collect all of my projects/snippets that aren't large/polished enough to make it on my portfolio.",
        tech: "React, Styled Components",
        grad: ["#CB356B", "#BD3F32"],
    },
    {
        id: "spotify-clone",
        name: "Spotify clone",
        github: "https://github.com/handcode-stuart/spotify-clone",
        website: "https://handcode-spotify-clone.herokuapp.com",
        bio: "An attempt to mimic the Spotify UI as close as possible.",
        tech: "React, SCSS",
        grad: ["#007991", "#78ffd6"],
    },
    {
        id: "circle-ci-test",
        name: "CircleCI test",
        github: "https://github.com/handcode-stuart/testing-react-ci",
        website: "https://handcode-react-testing.herokuapp.com",
        bio: "A simple React app with tests to utilise CircleCI and Heroku for CI.",
        tech: "React, Jest, Enzyme, CircleCI",
        grad: ["#9796f0", "#fbc7d4"],
    },
    {
        id: "task-list",
        name: "Local storage driven task list",
        github: "https://github.com/handcode-stuart/local-storage-task-list",
        website: "https://compassionate-panini-25f213.netlify.com",
        bio: "A simple task list app that uses local storage to persist tasks.",
        tech: "React, Local storage",
        grad: ["#5433FF", "#A5FECB"],
    },
    {
        id: "swansea-fc-interactive",
        name: "Swansea FC Interactive",
        github: "https://github.com/handcode-stuart/swanseafc-interactive",
        website: "https://admiring-bohr-1725f5.netlify.com",
        bio:
            "An interactive quiz/game that is current;y being displayed in Swansea FC's stadium store.",
        tech: "React, SCSS",
        grad: ["#FF5F6D", "#FFC371"],
    },
    {
        id: "smart-task-input",
        name: "Smart task input",
        github: "https://github.com/handcode-stuart/smart-task-input-react-component",
        website: "https://stoic-pasteur-294d1f.netlify.com/",
        bio: "A smart form input that checks for certain criteria, then maps those to state.",
        tech: "React",
        grad: ["#EECDA3", "#EF629F"],
    },
    {
        id: "react-node-auth",
        name: "ReactNodeAuth",
        github: "https://github.com/handcode-stuart/ReactNodeAuth",
        website: "",
        bio:
            "A boilerplate I created to speed up development of NodeJS, MongoDB, ReactJS & Redux applications.",
        tech: "React, NodeJS, Express, JWT",
        grad: ["#833ab4", "#fcb045"],
    },
    {
        id: "next-js",
        name: "NextJS",
        github: "https://github.com/handcode-stuart/nextjs-server-side-rendering-test",
        website: "https://learning-nextjs.stuart-handcode.now.sh/",
        bio: "A simple project to explore server side rendering.",
        tech: "React, NextJS",
        grad: ["#ED4264", "#FFEDBC"],
    },
    {
        id: "fpl-stats",
        name: "FPL stats",
        github: "https://github.com/handcode-stuart/fpl-stats",
        website: "https://trusting-fermi-8db60e.netlify.com",
        bio:
            "Using the now deprecated Fantasy Premier League API, this app was a way of seeing the player, team and match data in a different light to how the offical app showed.",
        tech: "React, Fantasy Premier League API, API consumption",
        grad: ["#bc4e9c", "#f80759"],
    },
    {
        id: "sales-taxes",
        name: "Sales Taxes",
        github: "https://github.com/handcode-stuart/sales_taxes",
        website: "https://protected-taiga-99206.herokuapp.com",
        bio: "A 'mock' store to show a simple tax calculator when a user puts items in their cart.",
        tech: "React, Redux, SCSS",
        grad: ["#159957", "#155799"],
    },
    {
        id: "user-app",
        name: "User app",
        github: "https://github.com/handcode-stuart/user-app",
        website: "https://stupefied-jackson-7ac0fd.netlify.com",
        bio: "A simple tool to display lists of contacts and multiple ways to view the content.",
        tech: "ReactJS, API consumption",
        grad: ["#800080", "#ffc0cb"],
    },
    {
        id: "map-user-data",
        name: "Map User Data",
        github: "https://github.com/handcode-stuart/map-user-data",
        website: "https://peaceful-pike-e61c64.netlify.com",
        bio: "An example of plotting users locations on a map from an API.",
        tech: "React, Redux, Custom hooks, Jest, Enzyme",
        grad: ["#0cebeb", "#29ffc6"],
    },
    {
        id: "site-saver",
        name: "Site Saver",
        github: "https://github.com/handcode-stuart/site-saver",
        website: "https://site-saver.handcodeapps.co.uk",
        bio: "A place to store bookmarks across multiple devices.",
        tech: "VueJS, Laravel, PHPUnit, TDD",
        grad: ["#83a4d4", "#b6fbff"],
    },
    {
        id: "side-hustle",
        name: "Side Hustle",
        github: "https://gitlab.com/handcode_stuart/side-hustle",
        website: "https://side-hustle.handcodeapps.co.uk",
        bio: "An area to work on different 'Side Hustle' ideas and collaborate with others.",
        tech: "VueJS, Laravel, PHPUnit, TDD",
        grad: ["#ddd6f3", "#faaca8"],
    },
];
