import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

const projects = [
    {
        id: 1,
        name: "CRM",
        github: "https://github.com/handcode-stuart/crm",
        website: "https://www.handcode.co.uk",
        bio:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vitae felis tempor, accumsan elit vel, egestas purus.",
        tech: "React, Redux, NodeJS, Express, JWT, MongoDB",
        grad: ["#C6FFDD", "#f7797d"],
    },
    {
        id: 2,
        name: "Orderly",
        github: "https://github.com/handcode-stuart/orderly",
        website: "https://www.handcode.co.uk",
        bio:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vitae felis tempor, accumsan elit vel, egestas purus.",
        tech: "React, Redux, NodeJS, Express, JWT, MongoDB",
        grad: ["#FF0099", "#493240"],
    },
    {
        id: 14,
        name: "Handcode - Worktop",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#CB356B", "#BD3F32"],
    },
    {
        id: 3,
        name: "FPL stats",
        github: "",
        website: "",
        bio: "",
        tech: "React, Fantasy Premier League API",
        grad: ["#bc4e9c", "#f80759"],
    },
    {
        id: 4,
        name: "Sales Taxes",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#159957", "#155799"],
    },
    {
        id: 5,
        name: "Spotify clone",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#007991", "#78ffd6"],
    },
    {
        id: 6,
        name: "Duckr",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#3494E6", "#EC6EAD"],
    },
    {
        id: 7,
        name: "Smart task input",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#EECDA3", "#EF629F"],
    },
    {
        id: 8,
        name: "Swansea FC",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#FF5F6D", "#FFC371"],
    },
    {
        id: 9,
        name: "ReactNodeAuth",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#833ab4", "#fcb045"],
    },
    {
        id: 10,
        name: "Site Saver",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#83a4d4", "#b6fbff"],
    },
    {
        id: 11,
        name: "Colllab",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#ddd6f3", "#faaca8"],
    },
    {
        id: 12,
        name: "Guestlist app",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#FC354C", "#0ABFBC"],
    },
    {
        id: 13,
        name: "NextJS test",
        github: "",
        website: "",
        bio: "",
        tech: "",
        grad: ["#ED4264", "#FFEDBC"],
    },
];

ReactDOM.render(<App projects={projects} />, document.querySelector("#root"));
